apiVersion: apps/v1
kind: Deployment
metadata:
  name: upcommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upcommerce-app
  template:
    metadata:
      labels:
        app: upcommerce-app
    spec:
      containers:
        - name: upcommerce
          image: uonyeka/upcommerce:v2 # Replace with your Docker image and tag
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: static
              mountPath: /app/static
            - name: templates
              mountPath: /app/templates
          imagePullPolicy: Always # Always pull the latest image
      volumes:
        - name: static
          emptyDir: {}
        - name: templates
          emptyDir: {}
